<h1>ADD POST</h1>
<form action="/Post" method="post" class="row g-3 needs-validation" novalidate>
    <div class="col-12">
        <label for="name" class="form-label">Title</label>
        <input type="text" class="form-control" id="name" value="Enter title" name="name" required>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
    <div class="col-12">
        <label for="content" class="form-label">Content</label>
        <textarea type="text" class="form-control" id="content" name="content" required></textarea>
        <div class="valid-feedback">
            Looks good!
        </div>
    </div>
      <div class="col-12">
        <button class="btn btn-primary" type="submit">Add Post</button>
    </div>
</form>